## **1. Import Library**

In [ ]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.4 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [ ]:
from google_play_scraper import app, reviews, Sort, reviews_all # Scraper from google play
import csv
import requests
from io import StringIO
import pandas as pd

## **2. Data Scraping**

In [ ]:
scrapreview = reviews(
    'notion.id',          # App ID
    lang='en',
    country='us',
    sort=Sort.MOST_RELEVANT,
    count = 15000 # Numbers of review to scrape
)

In [ ]:
app_reviews_df = pd.DataFrame(scrapreview[0])
jumlah_ulasan, jumlah_kolom = app_reviews_df.shape

In [ ]:
app_reviews_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,61a1c7ed-a0b0-420c-8a56-c44471365015,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,This was a fantastic app and superior alternat...,1,282,0.6.3287,2025-09-27 19:12:54,None,NaT,0.6.3287
1,b1bcf48a-2f1f-4625-a132-38ac06649c43,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,This app is great for organization and just wh...,4,5,0.6.1696,2026-02-26 21:47:37,None,NaT,0.6.1696
2,287d1da2-1cfc-417b-9d44-de7f70fcb9de,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,This app has become my second brain and awesom...,5,2,0.6.3684,2026-03-10 12:04:20,None,NaT,0.6.3684
3,ff46adac-9940-41b0-b226-88f27c75b130,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,The app version is horrible. I love using Noti...,3,0,0.6.3634,2026-02-16 06:25:56,None,NaT,0.6.3634
4,f59e80d8-fda6-4e74-8aff-5875bab9f5dd,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,The many free templates are a godsend. I use A...,5,31,0.6.3634,2026-02-15 03:02:09,None,NaT,0.6.3634

In [ ]:
# Menampilkan informasi tentang DataFrame app_reviews_df
app_reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              15000 non-null  object
 1   userName              15000 non-null  object
 2   userImage             15000 non-null  object
 3   content               15000 non-null  object
 4   score                 15000 non-null  int64
 5   thumbsUpCount         15000 non-null  int64
 6   reviewCreatedVersion  13234 non-null  object
 7   at                    15000 non-null  datetime64[ns]
 8   replyContent          140 non-null    object
 9   repliedAt             140 non-null    datetime64[ns]
 10  appVersion            13234 non-null  object
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 1.3+ MB

In [ ]:
app_reviews_df.isnull().sum()

reviewId                    0
userName                    0
userImage                   0
content                     0
score                       0
thumbsUpCount               0
reviewCreatedVersion     1766
at                          0
replyContent            14860
repliedAt               14860
appVersion               1766
dtype: int64

In [ ]:
app_reviews_df.duplicated().sum()

np.int64(0)

## **3. Data Preprocessing**

### Drop Irrelevant Features

In [ ]:
clean_df = app_reviews_df.drop(['reviewId', 'userName', 'userImage', 'at', 'replyContent', 'repliedAt', 'reviewCreatedVersion', 'appVersion'], axis=1)
clean_df = clean_df.dropna()
clean_df.to_csv('clean_data.csv', index=False)
clean_df.isnull().sum()

content          0
score            0
thumbsUpCount    0
dtype: int64

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   content        15000 non-null  object
 1   score          15000 non-null  int64
 2   thumbsUpCount  15000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 351.7+ KB

In [ ]:
clean_df.head()

                                             content  score  thumbsUpCount
0  This was a fantastic app and superior alternat...      1            282
1  This app is great for organization and just wh...      4              5
2  This app has become my second brain and awesom...      5              2
3  The app version is horrible. I love using Noti...      3              0
4  The many free templates are a godsend. I use A...      5             31